from io import BytesIO
import re
from datetime import date
from reportlab.pdfgen import canvas as rl_canvas
from reportlab.lib.pagesizes import A4
from reportlab.lib.colors import HexColor
from translator import TranslationResult


class ReportGenerationError(Exception):
    pass


# ── palette ─────────────────────────────────────────────────────────────────
BG      = HexColor("#0a0a0a")
ACCENT  = HexColor("#ffde00")
WHITE   = HexColor("#ffffff")
MUTED   = HexColor("#777777")
SURFACE = HexColor("#161616")
OK      = HexColor("#55cc77")
WARN    = HexColor("#ff8844")
DROP    = HexColor("#ff5555")

# ── page geometry ────────────────────────────────────────────────────────────
W, H    = A4          # 595.27 × 841.89 pt
MARGIN  = 40.0
IW      = W - 2 * MARGIN   # inner width
HEADER_H = 46.0
FOOTER_H = 24.0
CONTENT_TOP = H - HEADER_H - 12.0
CONTENT_BOT = FOOTER_H + 12.0

CONSOLE_NAMES = {
    "yamaha_cl": "Yamaha CL/QL",
    "digico_sd": "DiGiCo SD/Quantum",
}

_ACRONYMS = {"EQ", "HPF", "LPF", "VCA", "DSP", "MCA", "LCA", "RTA", "RMS", "PFL"}

_DEFAULT_NAME_RE = re.compile(
    r"^(?:CH|INPUT|IN|AUX|FX|BUS|DCA|VCA|MONO|ST)\s*\d+$", re.IGNORECASE
)


def _fmt_param(s: str) -> str:
    words = s.replace("_", " ").split()
    return " ".join(w.upper() if w.upper() in _ACRONYMS else w.title() for w in words)


def _is_default(ch) -> bool:
    """True when a channel carries no custom configuration."""
    has_custom_name = not _DEFAULT_NAME_RE.match(ch.name.strip())
    has_hpf  = ch.hpf_enabled
    has_eq   = any(abs(b.gain) > 0.05 for b in ch.eq_bands)
    has_gate = ch.gate is not None and ch.gate.enabled
    has_comp = ch.compressor is not None and ch.compressor.enabled
    return not (has_custom_name or has_hpf or has_eq or has_gate or has_comp)


def _ranges(ids: list[int]) -> list[tuple[int, int]]:
    if not ids:
        return []
    out, start, end = [], ids[0], ids[0]
    for n in ids[1:]:
        if n == end + 1:
            end = n
        else:
            out.append((start, end))
            start = end = n
    out.append((start, end))
    return out


def _range_str(ids: list[int]) -> str:
    parts = []
    for a, b in _ranges(ids):
        parts.append(f"Ch {a}" if a == b else f"Ch {a}-{b}")
    return ", ".join(parts)


# ── drawing helpers ──────────────────────────────────────────────────────────

def _chrome(c: rl_canvas.Canvas) -> None:
    """Draw background, header band, footer band."""
    # full-page background
    c.setFillColor(BG)
    c.rect(0, 0, W, H, fill=1, stroke=0)

    # header band
    c.setFillColor(ACCENT)
    c.rect(0, H - HEADER_H, W, HEADER_H, fill=1, stroke=0)
    c.setFillColor(HexColor("#000000"))
    c.setFont("Helvetica-Bold", 17)
    c.drawString(MARGIN, H - HEADER_H + 14, "SHOWFIER")
    c.setFont("Helvetica", 9)
    c.drawRightString(W - MARGIN, H - HEADER_H + 17, "TRANSLATION REPORT")

    # footer band
    c.setFillColor(SURFACE)
    c.rect(0, 0, W, FOOTER_H, fill=1, stroke=0)
    c.setFillColor(MUTED)
    c.setFont("Helvetica", 7)
    c.drawCentredString(
        W / 2, 8,
        "Generated by Showfier  -  Always verify all settings on the target console before the show"
    )


def _divider(c: rl_canvas.Canvas, y: float) -> float:
    c.setStrokeColor(HexColor("#2a2a2a"))
    c.setLineWidth(0.5)
    c.line(MARGIN, y, W - MARGIN, y)
    return y - 14


def _section_heading(c: rl_canvas.Canvas, y: float, text: str, color=None) -> float:
    c.setFillColor(color or ACCENT)
    c.setFont("Helvetica-Bold", 9)
    c.drawString(MARGIN, y, text)
    return y - 13


def generate_report(
    result: TranslationResult,
    source_console: str,
    target_console: str,
    source_filename: str = "",
    user_email: str = "",
) -> bytes:
    buf = BytesIO()
    c = rl_canvas.Canvas(buf, pagesize=A4)

    def new_page() -> float:
        _chrome(c)
        return CONTENT_TOP

    def need_space(y: float, needed: float) -> float:
        if y - needed < CONTENT_BOT:
            c.showPage()
            return new_page()
        return y

    # ── page 1 ──────────────────────────────────────────────────────────────
    y = new_page()

    # --- meta block ---------------------------------------------------------
    src_name = CONSOLE_NAMES.get(source_console, source_console)
    tgt_name = CONSOLE_NAMES.get(target_console, target_console)
    today    = date.today().strftime("%B %d, %Y")

    display_name = source_filename or "Unknown file"
    c.setFillColor(WHITE)
    c.setFont("Helvetica-Bold", 13)
    c.drawString(MARGIN, y, display_name)
    y -= 17

    c.setFillColor(ACCENT)
    c.setFont("Helvetica", 10)
    c.drawString(MARGIN, y, f"{src_name}  ->  {tgt_name}")
    y -= 13

    c.setFillColor(MUTED)
    c.setFont("Helvetica", 8)
    email_line = user_email if user_email else "Anonymous"
    c.drawString(MARGIN, y, f"{email_line}  |  {today}")
    y -= 22

    # --- stats row ----------------------------------------------------------
    channels      = getattr(result, "channels", [])
    active_chs    = [ch for ch in channels if not _is_default(ch)]
    default_chs   = [ch for ch in channels if _is_default(ch)]

    stats = [
        (str(len(active_chs)),                   "ACTIVE CHANNELS",     ACCENT),
        (str(len(result.translated_parameters)),  "PARAMS TRANSLATED",   OK),
        (str(len(result.dropped_parameters)),     "PARAMS DROPPED",      DROP if result.dropped_parameters else MUTED),
    ]
    card_w = IW / 3 - 5
    for i, (val, lbl, col) in enumerate(stats):
        cx = MARGIN + i * (card_w + 7)
        c.setFillColor(SURFACE)
        c.roundRect(cx, y - 34, card_w, 38, 4, fill=1, stroke=0)
        c.setFillColor(col)
        c.setFont("Helvetica-Bold", 20)
        c.drawCentredString(cx + card_w / 2, y - 16, val)
        c.setFillColor(MUTED)
        c.setFont("Helvetica", 7)
        c.drawCentredString(cx + card_w / 2, y - 28, lbl)
    y -= 52

    # --- warning box --------------------------------------------------------
    c.setFillColor(HexColor("#1a1400"))
    c.setStrokeColor(ACCENT)
    c.setLineWidth(0.8)
    c.roundRect(MARGIN, y - 30, IW, 34, 3, fill=1, stroke=1)
    c.setFillColor(ACCENT)
    c.setFont("Helvetica-Bold", 8)
    c.drawString(MARGIN + 8, y - 10, "(!) Always verify this file on the target console before the show.")
    c.setFillColor(MUTED)
    c.setFont("Helvetica", 7.5)
    c.drawString(MARGIN + 8, y - 22, "Load it, check the patch list, and spot-check EQ and dynamics on key channels.")
    y -= 46

    # ── channel summary ──────────────────────────────────────────────────────
    y = _divider(c, y)
    y = _section_heading(c, y, "CHANNEL SUMMARY")

    if not channels:
        c.setFillColor(MUTED)
        c.setFont("Helvetica", 8)
        c.drawString(MARGIN, y, "No channel data available.")
        y -= 13
    elif not active_chs:
        c.setFillColor(MUTED)
        c.setFont("Helvetica", 8)
        c.drawString(MARGIN, y, "All channels used console defaults.")
        y -= 13
    else:
        # column header row
        COL_X = {
            "ch":   MARGIN,
            "name": MARGIN + 30,
            "hpf":  MARGIN + 170,
            "eq":   MARGIN + 230,
            "gate": MARGIN + 280,
            "comp": MARGIN + 330,
        }
        c.setFillColor(MUTED)
        c.setFont("Helvetica-Bold", 7)
        for label, x in [("CH", COL_X["ch"]), ("NAME", COL_X["name"]),
                          ("HPF", COL_X["hpf"]), ("EQ", COL_X["eq"]),
                          ("GATE", COL_X["gate"]), ("COMP", COL_X["comp"])]:
            c.drawString(x, y, label)
        y -= 4
        c.setStrokeColor(HexColor("#2a2a2a"))
        c.setLineWidth(0.5)
        c.line(MARGIN, y, W - MARGIN, y)
        y -= 10

        for idx, ch in enumerate(active_chs):
            y = need_space(y, 14)

            # subtle alternating row tint
            if idx % 2 == 0:
                c.setFillColor(HexColor("#111111"))
                c.rect(MARGIN - 4, y - 4, IW + 8, 13, fill=1, stroke=0)

            c.setFillColor(MUTED)
            c.setFont("Helvetica", 8)
            c.drawString(COL_X["ch"], y, str(ch.id))

            c.setFillColor(WHITE)
            c.setFont("Helvetica-Bold", 8)
            name = ch.name[:20] if len(ch.name) > 20 else ch.name
            c.drawString(COL_X["name"], y, name)

            c.setFont("Helvetica", 8)
            if ch.hpf_enabled:
                c.setFillColor(OK)
                c.drawString(COL_X["hpf"], y, f"{ch.hpf_frequency:.0f}Hz")
            else:
                c.setFillColor(MUTED)
                c.drawString(COL_X["hpf"], y, "-")

            active_eq = [b for b in ch.eq_bands if abs(b.gain) > 0.05]
            if active_eq:
                c.setFillColor(OK)
                c.drawString(COL_X["eq"], y, f"{len(active_eq)}bd")
            else:
                c.setFillColor(MUTED)
                c.drawString(COL_X["eq"], y, "-")

            if ch.gate and ch.gate.enabled:
                c.setFillColor(OK)
                c.drawString(COL_X["gate"], y, f"{ch.gate.threshold:.0f}dB")
            else:
                c.setFillColor(MUTED)
                c.drawString(COL_X["gate"], y, "-")

            if ch.compressor and ch.compressor.enabled:
                c.setFillColor(OK)
                c.drawString(COL_X["comp"], y, f"{ch.compressor.ratio:.1f}:1")
            else:
                c.setFillColor(MUTED)
                c.drawString(COL_X["comp"], y, "-")

            y -= 13

    # default channels footnote
    if default_chs:
        y = need_space(y, 36)
        y -= 6
        ids = sorted(ch.id for ch in default_chs)
        note = f"{_range_str(ids)} - Default settings. Target console defaults applied."
        c.setFillColor(SURFACE)
        c.roundRect(MARGIN, y - 26, IW, 30, 3, fill=1, stroke=0)
        c.setFillColor(MUTED)
        c.setFont("Helvetica", 8)
        c.drawString(MARGIN + 8, y - 8, note)
        c.setFont("Helvetica", 7)
        c.drawString(MARGIN + 8, y - 19,
                     "These channels had no custom config and are omitted from the listing above.")
        y -= 40

    # ── parameter summary ────────────────────────────────────────────────────
    y = need_space(y, 20)
    y = _divider(c, y)

    def param_section(title: str, items: list[str], col) -> None:
        nonlocal y
        y = need_space(y, 16 + len(items) * 11)
        y = _section_heading(c, y, title, col)
        if not items:
            c.setFillColor(MUTED)
            c.setFont("Helvetica", 8)
            c.drawString(MARGIN + 10, y, "None")
            y -= 11
        else:
            for item in items:
                c.setFillColor(WHITE)
                c.setFont("Helvetica", 8)
                c.drawString(MARGIN + 10, y, f"- {_fmt_param(item)}")
                y -= 11
        y -= 5

    param_section("TRANSLATED SUCCESSFULLY",        result.translated_parameters,  OK)
    param_section("APPROXIMATED  (verify on desk)", result.approximated_parameters, ACCENT)
    param_section("DROPPED  (not available on target)", result.dropped_parameters,  DROP)

    try:
        c.save()
    except Exception as e:
        raise ReportGenerationError(f"Failed to build PDF: {e}") from e

    return buf.getvalue()
